// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs-J7K4nDlmzKlFuqgpZKLt-13hfC-Pe8',
    appId: '1:1047488648683:web:6522f17b47abd1c63cb5ae',
    messagingSenderId: '1047488648683',
    projectId: 'chat-app-f7efc',
    authDomain: 'chat-app-f7efc.firebaseapp.com',
    storageBucket: 'chat-app-f7efc.appspot.com',
    measurementId: 'G-MBQ1QJQJS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeOEZ1ThGEA0jsKz5C-nFF07h8Ivycvkk',
    appId: '1:1047488648683:android:0932e0652898147f3cb5ae',
    messagingSenderId: '1047488648683',
    projectId: 'chat-app-f7efc',
    storageBucket: 'chat-app-f7efc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvSEPHNGBS15qHdR9eLFyRRn-zSHF1owc',
    appId: '1:1047488648683:ios:399788b969c3ed9d3cb5ae',
    messagingSenderId: '1047488648683',
    projectId: 'chat-app-f7efc',
    storageBucket: 'chat-app-f7efc.appspot.com',
    iosClientId: '1047488648683-1mkhl9r662shrfghb5emaa0g6f1dbabc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvSEPHNGBS15qHdR9eLFyRRn-zSHF1owc',
    appId: '1:1047488648683:ios:96168d90c6e2cca23cb5ae',
    messagingSenderId: '1047488648683',
    projectId: 'chat-app-f7efc',
    storageBucket: 'chat-app-f7efc.appspot.com',
    iosClientId: '1047488648683-vdoc23d3upbfd3q6uqucb6catd98ngsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
